[tool.poetry]
name = "14"
version = "0.1.0"
description = ""
authors = ["Håvard Anda Estensen <haavard.ae@gmail.com>"]

[tool.poetry.dependencies]
python = "^2.7"
requests = "^2.21"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
